Título: The World's Biggest Companies 2021

URL: https://www.kaggle.com/berkayalan/the-worlds-biggest-companies-2021

Introducción
Las modernas economías capitalistas habían sido consideradas economías de mercado hasta los últimos años, pero se ha probado que las grandes corporaciones juegan un rol muy importante en la economía, esto significa que las grandes empresas y corporaciones deciden el desarrollo de la economía actual.
Las corporaciones multinacionales son las dedicadas al desarrollo de una actividad (es) en varios países, donde buscará mayor crecimiento de sus operaciones, una mayor expansión de sus actividades, teniendo como resultado importante el crecimiento económico, dado los bajos costos que permitirán bajos precios y una ampliación de su mercado.
Las empresas multinacionales (EMN) o empresas transnacionales son aquéllas que no sólo están establecidas en su país de origen, sino que también se constituyen en otros países para realizar sus actividades mercantiles tanto de venta y compra como de producción en los países donde se han establecido.
Las multinacionales están en capacidad de expandir la producción y otras operaciones alrededor del mundo, así como de movilizar plantas industriales de un país a otro. Los procesos de fusión y las alianzas entre ellas, les permiten alcanzar un creciente poder e influencia en la economía mundial.


Dentro de las columnas de la tabla podemos observar el ranking, el nombre de las empresas, su lugar de origen sus ventas, su profit y sus activos, la mayoría de estos en datos numéricos con 2 excepciones.
Lo que nos llama la atención de esta base de datos es que podemos ver las empresas más grandes del mundo, con todos los datos que se pudimos ver antes. Todo estos daros sacados de FORBES. Los beneficios de trabajar con esta base de datos es que podemos ver todos los datos financieros de las mejores compañías hoy en día.
Como objetivo principal tenemos el conocer los datos financieros de las compañías que están dentro de la base de datos.

In [ ]:
import pandas as pd
import numpy as np
import json

df = pd.read_csv("/content/Base_Secunadria.csv", index_col=0, encoding="latin-1")

In [ ]:
df.shape
df.head()

                                                          Unnamed: 1
Rank;Name;Country;Sales;Profit;Assets;Market Value
1;ICBC;China;$190.5 B;$45.8 B;$4                    914.7 B;$249.5 B
2;JPMorgan Chase;United States;$136.2 B;$40.4 B;$3  689.3 B;$464.8 B
3;Berkshire Hathaway;United States;$245.5 B;$42...               NaN
4;China Construction Bank;China;$173.5 B;$39.3 ...  301.7 B;$210.4 B
5;Saudi Arabian Oil Company (Saudi Aramco);Saud...           897.2 B

In [ ]:
df.rename(columns = {'Name':'Nombre'})
df.rename(columns = {'Country':'Pais'})
df.isnull()

                                                    Unnamed: 1
Rank;Name;Country;Sales;Profit;Assets;Market Value
1;ICBC;China;$190.5 B;$45.8 B;$4                         False
2;JPMorgan Chase;United States;$136.2 B;$40.4 B;$3       False
3;Berkshire Hathaway;United States;$245.5 B;$42...        True
4;China Construction Bank;China;$173.5 B;$39.3 ...       False
5;Saudi Arabian Oil Company (Saudi Aramco);Saud...       False
...                                                        ...
496;CSL;Australia;$9.9 B;$2.6 B;$17.7 B;$94.7 B           True
497;Safran;France;$19 B;$401.3 M;$48.4 B;$66.8 B          True
498;Banorte;Mexico;$9.4 B;$1.4 B;$89.7 B;$17.6 B          True
498;KeyCorp;United States;$7.3 B;$1.3 B;$170.3 ...        True
500;Lufax Holding;China;$8.3 B;$1.8 B;$38.1 B;$...        True

[500 rows x 1 columns]